modLoader = "javafml"
loaderVersion = "[40,)"
license = "AGPL-3.0+ALEC"

issueTrackerURL = "https://git.tilera.org/Anvilcraft/ntx4core/issues"

[[mods]]
modId = "ntx4core"
version = "${version}"
displayName = "ntx4core"
displayURL = "https://anvilcraft.net/"
#credits = ""
authors = "LordMZTE, (tilera)"

description = '''
Core for Notex 4.

Includes recipes and tweaks.
'''

[[dependencies.ntx4core]]
modId = "forge"
mandatory = true

versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ntx4core]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.ntx4core]]
modId = "geckolib3"
mandatory = true
versionRange = "[3.0.57,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ntx4core]]
modId = "anvillib"
mandatory = true
versionRange = "[0.2.0,)"
ordering = "NONE"
side = "BOTH"